### ISSUE TITLE
Downloads are very slow

### ISSUE THREAD

**Issue by Alphare** [ccgauche/ytermusic#30] opened 2022-11-25 16:18 UTC
The current behavior when the user opens a playlist is to start 4 parallel jobs to download 4 (arbitrary?) songs from the playlist to local cache, then start playing as soon as one is available. 

Since streaming is not yet an option, I see two things that would greatly improve the user experience:
 - ensuring that the user has at least one song to play as fast as possible
 - allowing the user to override the current preferred song to download

The second one should be its own issue because it opens other questions of UI (do we have a way of showing all songs in the playlist and giving control etc.), I only mention it here to be thorough.

When I look at my drive activity, I see that `ytermusic` is only writing at ~120kb/s when downloading the videos, which is much, much slower than either my gigabit ethernet or my PCIE-4 NVME SSD are capable of handling. This results in having to wait more than 1 minute to start playing *a* song (and I say *a* song because I can't really choose which one is being downloaded yet), while 3 others are at 80% completion.

Is there a hard reason why we can't download faster from Youtube? If so, investigating streaming might be the path forwards. On the other hand, if we're limited by the implementation somehow, is the async download pool slow because it's trying to be too clever and not prioritize enough, etc?

**Comment by ccgauche** [comment] 2022-11-25 17:12
There is few things to note:
 - Downloads are very slow, I bet this is youtube limiting the speed to what you can listen to.
 - Another option would be that the downloader implementation in rustube is really slow (There are using 10kb chunks so maybe the issue is here)
 - This maybe worth investigating or rustube side

**Comment by ccgauche** [comment] 2022-11-25 17:18
Seems that youtube is slowing downloads to non-player accesses:
https://github.com/dirkf/youtube-dl/commit/cf001636600430b4b03963238c14a11c33d6d013
So they changed their security and if you aren't using the new system you get slowed down.

**Comment by ccgauche** [comment] 2022-11-25 17:21
https://github.com/DzenanJupic/rustube/issues/37
A fix would be to change the chunk size to >10Mb but this will increase RAM usage a lot. Still it would be better than slow downloads

**Comment by Alphare** [comment] 2022-11-25 17:26
IMO having the player consume 10Mb per download worker is really not unreasonable. This could be configurable if RAM constraints are really a problem, but chances are that the primary use case it so have a download as fast as possible to start playing music. This is only a problem because streaming isn't possible, again. :)

**Comment by ccgauche** [comment] 2022-11-26 11:48
https://github.com/ytdl-org/youtube-dl/pull/30184/files in _unthrottle_format_urls

**Comment by ccgauche** [comment] 2022-11-28 10:48
@Alphare I looked a bit to what is required to make this work and clearly it's a LOT of work like hundred of lines of code. unthrottling seems even more complicated than download videos

**Comment by ccgauche** [comment] 2022-11-28 10:51
@Alphare It's on the RustTube side I could try fixing it myself but it'll make lots of time and will be very complicated. The PyTube solution is maybe better since they aren't interpreting the JS code and just hacking it. While YtDl took the path of interpreting the JS easing the implementation but having to ship a JS interpreter. BOA in rust is probably good enough but still I would rather avoid interpreters shipped with YT-Music

**Comment by ccgauche** [comment] 2022-11-29 15:44
@Alphare I started working on a fix but IDK why it doesn't work (Seems like an infinite loop) (I generated the code using Copilot to convert it from Python (PyTube project)) It probably missed something somewhere but need more investigation https://github.com/ccgauche/rustube

**Comment by ccgauche** [comment] 2022-11-30 12:50
Fixed in commit 9bf984f41457d6a715a86ff8e9b304368194b924 using my own fix in rustube. I'll try to merge it but it needs some cleanup https://github.com/Discursif/rustube

**Closed by ccgauche** 2022-11-30 12:50 UTC
Labels: bug, network

**Comment by Alphare** [comment] 2022-11-30 13:24
FYI this seems to work flawlessly. Now the downloads are as fast as they could possibly be. :)
